Repository MetaMask/design-tokens, pull requests merged in 2022-02, with the labels that each got.

#20 Add issue template
  .github/ISSUE_TEMPLATE/general_issue.md
Labels: needs-dev-review

#19 Adding storybook and design token documentation
  .eslintrc.js
  .storybook/main.js
  .storybook/preview.js
  README.md
  docs/BrandColors.mdx
  docs/BrandColors.stories.tsx
  docs/Introduction.stories.mdx
  docs/IntroductionColor.stories.mdx
  docs/ThemeColors.mdx
  docs/ThemeColors.stories.tsx
  docs/components/ColorSwatch/ColorSwatch.tsx
  docs/components/ColorSwatch/index.tsx
  docs/components/ColorSwatchGroup/ColorSwatchGroup.tsx
  docs/components/ColorSwatchGroup/index.tsx
  docs/components/index.tsx
  docs/images/design.token.graphic.svg
  package.json
  tsconfig.json
  yarn.lock
Labels: documentation

#22 Color token updates
  src/colors/index.ts
  src/css/design-tokens.css
  src/figma/tokens.json
Labels: color
