Repository MetaMask/design-tokens, pull requests merged in 2024-05, with the labels that each got.

#677 feat: Reorganize CSS variables and added brand evolution colors
  src/css/brand-colors-brand-evolution.css
  src/css/brand-colors.css
  src/css/dark-theme-brand-evolution.css
  src/css/dark-theme.css
  src/css/design-tokens-brand-evolution.css
  src/css/light-theme-brand-evolution.css
  src/css/light-theme.css
  src/css/shadow.css
  src/css/typography.css
Labels: team-design-system

#676 chore: refactoring css and improving build to adhere to workspace conventions
  .storybook/preview.ts
  MIGRATION.md
  README.md
  docs/fonts/fonts.css
  package.json
  src/css/brand-colors.css
  src/css/dark-theme-colors.css
  src/css/index.css
  src/css/light-theme-colors.css
  src/css/shadow.css
  src/css/typography.css
  yarn.config.cjs
  yarn.lock
Labels: team-design-system

#679 chore: clean up json
  src/figma/darkTheme.json
  src/figma/lightTheme.json
Labels: team-design-system

#689 docs: updating readme to add tooling section that links to eslint-plugin
  README.md
Labels: team-design-system

#693 fix: Icon alternative color fix
  src/css/light-theme-colors-brand-evolution.css
  src/css/light-theme-colors.css
Labels: color, team-design-system

#694 fix: Icon alternative fix in brand evolution branch
  src/css/light-theme-colors.css
Labels: color, team-design-system

#696 fix: css stories use css variables instead of static color values
  docs/BrandColors.stories.tsx
  docs/ThemeColors.stories.tsx
  docs/components/ColorSwatch/ColorSwatch.tsx
Labels: bug, documentation

#699 fix: fix lint errors in utils
  docs/utils/getCSSVariablesFromStylesheet.ts
  docs/utils/useJsonColor.ts
Labels: color, team-design-system

#702 fix: updating brand color figma json
  src/figma/brandColors.json
  src/figma/brandColorsBrandEvolution.json
  src/figma/darkTheme.json
  src/figma/lightTheme.json
Labels: team-design-system

#706 chore: updating doc components and helpers
  docs/BrandColors.stories.tsx
  docs/ThemeColors.stories.tsx
  docs/components/ColorSwatchGroup/ColorSwatchGroup.tsx
  docs/utils/getContrastYIQ.ts
  docs/utils/getJSColors.ts
  docs/utils/index.ts
  docs/utils/useJsonColor.ts
  src/figma/brandColors.json
Labels: team-design-system

#703 chore: upgrading storybook to 8.1.4
  .storybook/preview.ts
  package.json
  yarn.lock
Labels: team-design-system

#715 chore: adding overlay.inverse colors to json
  src/figma/darkTheme.json
  src/figma/lightTheme.json
Labels: team-design-system

#708 chore: updated css variables based on updated json
  MIGRATION.md
  src/css/brand-colors.css
  src/css/dark-theme-colors.css
  src/css/light-theme-colors.css
Labels: color, team-design-system

#709 chore: updated js variables based on updated json
  MIGRATION.md
  src/js/brandColor/brandColor.test.ts
  src/js/brandColor/brandColor.ts
  src/js/brandColor/brandColor.types.ts
  src/js/themes/darkTheme/colors.test.ts
  src/js/themes/darkTheme/colors.ts
  src/js/themes/darkTheme/darkTheme.test.ts
  src/js/themes/darkTheme/shadows.test.ts
  src/js/themes/lightTheme/colors.test.ts
  src/js/themes/lightTheme/colors.ts
  src/js/themes/lightTheme/lightTheme.test.ts
  src/js/themes/lightTheme/shadows.test.ts
  src/js/themes/types.ts
Labels: color, team-design-system
