Repository MetaMask/design-tokens, pull requests merged in 2024-01, with the labels that each got.

#538 devDeps: storybook v7
  .babelrc.json
  .storybook/main.js
  docs/Introduction.stories.mdx
  package.json
  yarn.lock
Labels: dependencies

#582 Adding brand colors to CSSinJS exports
  src/js/brandColors/brandColors.test.ts
  src/js/brandColors/brandColors.ts
  src/js/brandColors/brandColors.types.ts
  src/js/brandColors/index.ts
  src/js/index.ts
Labels: team-design-system

#589 Revert "Adding brand colors to CSSinJS exports"
  src/js/brandColors/brandColors.test.ts
  src/js/brandColors/brandColors.ts
  src/js/brandColors/brandColors.types.ts
  src/js/brandColors/index.ts
  src/js/index.ts
Labels: team-design-system

#593 Updating documentation
  README.md
  docs/BrandColors.mdx
  docs/BrandColors.stories.tsx
  docs/IntroductionColor.stories.mdx
  docs/Shadows.mdx
  docs/Shadows.stories.tsx
  docs/ThemeColors.mdx
  docs/ThemeColors.stories.tsx
  docs/Typography.mdx
  docs/Typography.stories.tsx
  docs/components/ColorSwatchGroup/ColorSwatchGroup.tsx
Labels: documentation, color

#585 Refactoring the brand color object
  docs/BrandColors.stories.tsx
  src/index.ts
  src/js/brandColor/brandColor.test.ts
  src/js/brandColor/brandColor.ts
  src/js/brandColor/brandColor.types.ts
  src/js/brandColor/index.ts
  src/js/index.ts
Labels: team-design-system
